[package]
name = "bgpkit-parser"
version = "0.6.0-rc.1"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/bgpkit/bgpkit-parser"
documentation = "https://docs.rs/bgpkit-parser"
description = """
A library to parse MRT/BGP/BMP binary data.
"""
keywords = ["bgp", "bgpkit", "mrt"]

[dependencies]
byteorder = "1.2"
ipnetwork = "0.18"
enum-primitive-derive = "0.1"
num-traits = "0.1"
chrono = "0.4"
bgp-models = "0.3.4"

# logging
log="0.4"
env_logger="0.9"
itertools = "0.10.1"

bzip2="0.4.3"
flate2="1.0.22"
reqwest = { version = "0.11", features = ["json", "blocking", "stream"]}


# ris-live parsing
serde={version="1.0.130", features=["derive"]}
serde_json = "1.0.69"

# bmp/openbmp parsing
hex="0.4.3"

[dev-dependencies]
bgpkit-broker = "0.3.2"
kafka = "0.8"

# websocket
tungstenite="0.16.0"
url = "2.1.0"
