name: formatting

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Run format check
      run: cargo fmt --check

    - name: Run cargo-readme check
      run: cargo readme > TMP_README.md && diff -b TMP_README.md README.md