name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test --all-features

    - name: Run format check
      run: cargo fmt --check

    - name: Run cargo-readme check
      run: cargo readme > TMP_README.md && diff -b TMP_README.md README.md

    - name: Run clippy
      run: cargo clippy --all-features -- -D warnings